# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Domain-Registry-VeriSign
version:      0.01
version_from: lib/WWW/Domain/Registry/VeriSign.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Test::More:                    0.62
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
